import './global.sass';
import App from './components/app/app';
const data = [
    {
        id: 1,
        discount_value: 0,
        discount: false,
        image: {
            src: './assets/images/AHMAD.jpg',
        },
        brand: 'AHMAD TEE',
        type: 'чай',
        box: 'листовой',
        color: 'черный',
        country: 'Индия',
        price: 10,
        date: 2019,
    },
    {
        id: 3,
        discount_value: 10,
        discount: true,
        image: {
            src: './assets/images/lipton.jpg',
        },
        brand: 'LIPTON',
        type: 'чай',
        box: 'пакетированный',
        color: 'черный',
        country: 'Индонезия',
        price: 12,
        date: 2021,
    },
    {
        id: 2,
        discount_value: 0,
        discount: false,
        image: {
            src: './assets/images/greenfield.png',
        },
        brand: 'GREENFIELD',
        type: 'чай',
        box: 'листовой',
        color: 'зеленый',
        country: 'Китай',
        price: 13,
        date: 2020,
    },
    {
        id: 4,
        discount_value: 0,
        discount: false,
        image: {
            src: './assets/images/richard.jpg',
        },
        brand: 'RICHARD',
        type: 'чай',
        box: 'листовой',
        color: 'черный',
        country: 'Англия',
        price: 200,
        date: 2022,
    },
    {
        id: 5,
        discount_value: 30,
        discount: true,
        image: {
            src: './assets/images/greenfield.png',
        },
        brand: 'Greenfield',
        type: 'чай',
        box: 'листовой',
        color: 'зеленый',
        country: 'Индия',
        price: 140,
        date: 2022,
    },
    {
        id: 6,
        discount_value: 50,
        discount: true,
        image: {
            src: './assets/images/richard.jpg',
        },
        brand: 'RICHARD',
        type: 'чай',
        box: 'листовой',
        color: 'черный',
        country: 'Китай',
        price: 2670,
        date: 2022,
    },
    {
        id: 7,
        discount_value: 52,
        discount: true,
        image: {
            src: './assets/images/richard.jpg',
        },
        brand: 'RICHARD',
        type: 'чай',
        box: 'листовой',
        color: 'черный',
        country: 'Китай',
        price: 2670,
        date: 2022,
    },
    {
        id: 8,
        discount_value: 520,
        discount: true,
        image: {
            src: './assets/images/richard.jpg',
        },
        brand: 'RICHARD',
        type: 'чай',
        box: 'листовой',
        color: 'черный',
        country: 'Китай',
        price: 2670,
        date: 2022,
    },
    {
        id: 9,
        discount_value: 42,
        discount: true,
        image: {
            src: './assets/images/richard.jpg',
        },
        brand: 'RICHARD',
        type: 'чай',
        box: 'листовой',
        color: 'черный',
        country: 'Китай',
        price: 2670,
        date: 2022,
    },
    {
        id: 10,
        discount_value: 50,
        discount: true,
        image: {
            src: './assets/images/richard.jpg',
        },
        brand: 'RICHARD',
        type: 'чай',
        box: 'листовой',
        color: 'черный',
        country: 'Китай',
        price: 2670,
        date: 2022,
    },
    {
        id: 11,
        discount_value: 50,
        discount: true,
        image: {
            src: './assets/images/richard.jpg',
        },
        brand: 'RICHARD',
        type: 'чай',
        box: 'листовой',
        color: 'черный',
        country: 'Китай',
        price: 2670,
        date: 2022,
    },
    {
        id: 12,
        discount_value: 50,
        discount: true,
        image: {
            src: './assets/images/richard.jpg',
        },
        brand: 'RICHARD',
        type: 'чай',
        box: 'листовой',
        color: 'черный',
        country: 'Китай',
        price: 2670,
        date: 2022,
    },
    {
        id: 13,
        discount_value: 50,
        discount: true,
        image: {
            src: './assets/images/richard.jpg',
        },
        brand: 'RICHARD',
        type: 'чай',
        box: 'листовой',
        color: 'черный',
        country: 'Китай',
        price: 2670,
        date: 2022,
    },
    {
        id: 14,
        discount_value: 50,
        discount: true,
        image: {
            src: './assets/images/richard.jpg',
        },
        brand: 'RICHARD',
        type: 'чай',
        box: 'листовой',
        color: 'черный',
        country: 'Китай',
        price: 2670,
        date: 2022,
    },
    {
        id: 15,
        discount_value: 50,
        discount: true,
        image: {
            src: './assets/images/richard.jpg',
        },
        brand: 'RICHARD',
        type: 'чай',
        box: 'листовой',
        color: 'черный',
        country: 'Китай',
        price: 2670,
        date: 2022,
    },
    {
        id: 16,
        discount_value: 50,
        discount: true,
        image: {
            src: './assets/images/richard.jpg',
        },
        brand: 'RICHARD',
        type: 'чай',
        box: 'листовой',
        color: 'черный',
        country: 'Китай',
        price: 2670,
        date: 2022,
    },
    {
        id: 17,
        discount_value: 50,
        discount: true,
        image: {
            src: './assets/images/richard.jpg',
        },
        brand: 'RICHARD',
        type: 'чай',
        box: 'листовой',
        color: 'черный',
        country: 'Китай',
        price: 2670,
        date: 2022,
    },
    {
        id: 18,
        discount_value: 50,
        discount: true,
        image: {
            src: './assets/images/richard.jpg',
        },
        brand: 'RICHARD',
        type: 'чай',
        box: 'листовой',
        color: 'черный',
        country: 'Китай',
        price: 2670,
        date: 2022,
    },
    {
        id: 19,
        discount_value: 50,
        discount: true,
        image: {
            src: './assets/images/richard.jpg',
        },
        brand: 'RICHARD',
        type: 'чай',
        box: 'листовой',
        color: 'черный',
        country: 'Китай',
        price: 2670,
        date: 2022,
    },
    {
        id: 20,
        discount_value: 50,
        discount: true,
        image: {
            src: './assets/images/richard.jpg',
        },
        brand: 'RICHARD',
        type: 'чай',
        box: 'листовой',
        color: 'черный',
        country: 'Китай',
        price: 2670,
        date: 2022,
    },
    {
        id: 21,
        discount_value: 50,
        discount: true,
        image: {
            src: './assets/images/richard.jpg',
        },
        brand: 'RICHARD',
        type: 'чай',
        box: 'листовой',
        color: 'черный',
        country: 'Китай',
        price: 2670,
        date: 2022,
    },
];
const APP = new App(data);
APP.start();
