import { TCards } from '../types/types';

export const data: TCards = [
    {
        id: 1,
        discount_value: 0,
        discount: false,
        image: {
            src: './assets/images/AHMAD.jpg',
        },
        brand: 'AHMAD TEA',
        type: 'чай',
        box: 'листовой',
        color: 'черный',
        country: 'Индия',
        price: 10,
        date: 2019,
    },
    {
        id: 3,
        discount_value: 10,
        discount: true,
        image: {
            src: './assets/images/lipton.jpg',
        },
        brand: 'LIPTON',
        type: 'чай',
        box: 'пакетированный',
        color: 'черный',
        country: 'Индонезия',
        price: 12,
        date: 2021,
    },
    {
        id: 2,
        discount_value: 0,
        discount: false,
        image: {
            src: './assets/images/AHMAD_red.jpg',
        },
        brand: 'AHMAD TEA',
        type: 'чай',
        box: 'пакетированный',
        color: 'красный',
        country: 'Индия',
        price: 13,
        date: 2020,
    },
    {
        id: 4,
        discount_value: 0,
        discount: false,
        image: {
            src: './assets/images/richard.jpg',
        },
        brand: 'RICHARD',
        type: 'чай',
        box: 'листовой',
        color: 'черный',
        country: 'Англия',
        price: 5,
        date: 2022,
    },
    {
        id: 5,
        discount_value: 30,
        discount: true,
        image: {
            src: './assets/images/greenfield.png',
        },
        brand: 'Greenfield',
        type: 'чай',
        box: 'листовой',
        color: 'зеленый',
        country: 'Китай',
        price: 30,
        date: 2022,
    },
    {
        id: 6,
        discount_value: 50,
        discount: true,
        image: {
            src: './assets/images/richard_white.jpg',
        },
        brand: 'RICHARD',
        type: 'чай',
        box: 'листовой',
        color: 'белый',
        country: 'Англия',
        price: 22,
        date: 2022,
    },
    {
        id: 7,
        discount_value: 52,
        discount: true,
        image: {
            src: './assets/images/curtis_black.jpg',
        },
        brand: 'CURTIS',
        type: 'чай',
        box: 'листовой',
        color: 'черный',
        country: 'Индонезия',
        price: 7,
        date: 2018,
    },
    {
        id: 8,
        discount_value: 520,
        discount: true,
        image: {
            src: './assets/images/curtis_green_pack.jpg',
        },
        brand: 'CURTIS',
        type: 'чай',
        box: 'пакетированный',
        color: 'зеленый',
        country: 'Индонезия',
        price: 13,
        date: 2017,
    },
    {
        id: 9,
        discount_value: 42,
        discount: true,
        image: {
            src: './assets/images/impra_black.jpg',
        },
        brand: 'IMPRA',
        type: 'чай',
        box: 'листовой',
        color: 'черный',
        country: 'Англия',
        price: 24,
        date: 2018,
    },
    {
        id: 10,
        discount_value: 50,
        discount: true,
        image: {
            src: './assets/images/impra_green.jpg',
        },
        brand: 'IMPRA',
        type: 'чай',
        box: 'листовой',
        color: 'зеленый',
        country: 'Англия',
        price: 15,
        date: 2020,
    },
    {
        id: 11,
        discount_value: 50,
        discount: true,
        image: {
            src: './assets/images/impra_red.jpg',
        },
        brand: 'IMPRA',
        type: 'чай',
        box: 'листовой',
        color: 'красный',
        country: 'Англия',
        price: 10,
        date: 2022,
    },
    {
        id: 12,
        discount_value: 50,
        discount: true,
        image: {
            src: './assets/images/AHMAD_white.jpg',
        },
        brand: 'AHMAD TEA',
        type: 'чай',
        box: 'листовой',
        color: 'белый',
        country: 'Индия',
        price: 21,
        date: 2022,
    },
    {
        id: 13,
        discount_value: 50,
        discount: true,
        image: {
            src: './assets/images/curtis_white.jpg',
        },
        brand: 'CURTIS',
        type: 'чай',
        box: 'листовой',
        color: 'белый',
        country: 'Индонезия',
        price: 22.5,
        date: 2018,
    },
    {
        id: 14,
        discount_value: 50,
        discount: true,
        image: {
            src: './assets/images/richard.jpg',
        },
        brand: 'RICHARD',
        type: 'чай',
        box: 'листовой',
        color: 'черный',
        country: 'Китай',
        price: 14.2,
        date: 2022,
    },
    {
        id: 15,
        discount_value: 50,
        discount: true,
        image: {
            src: './assets/images/lipton_green.webp',
        },
        brand: 'Lipton',
        type: 'чай',
        box: 'пакетированный',
        color: 'зеленый',
        country: 'Индия',
        price: 13.2,
        date: 2022,
    },
    {
        id: 16,
        discount_value: 10,
        discount: true,
        image: {
            src: './assets/images/lipton_red.jpg',
        },
        brand: 'Lipton',
        type: 'чай',
        box: 'пакетированный',
        color: 'черный',
        country: 'Англия',
        price: 5.5,
        date: 2021,
    },
    {
        id: 17,
        discount_value: 0,
        discount: false,
        image: {
            src: './assets/images/lipton-white.jpg',
        },
        brand: 'Lipton',
        type: 'чай',
        box: 'пакетированный',
        color: 'черный',
        country: 'Англия',
        price: 10,
        date: 2021,
    },
    {
        id: 18,
        discount_value: 0,
        discount: false,
        image: {
            src: './assets/images/richard_red.jpg',
        },
        brand: 'RICHARD',
        type: 'чай',
        box: 'пакетированный',
        color: 'красный',
        country: 'Англия',
        price: 19.99,
        date: 2020,
    },
    {
        id: 19,
        discount_value: 0,
        discount: false,
        image: {
            src: './assets/images/richard_green.jpg',
        },
        brand: 'RICHARD',
        type: 'чай',
        box: 'листовой',
        color: 'зеленый',
        country: 'Англия',
        price: 10,
        date: 2019,
    },
    {
        id: 20,
        discount_value: 0,
        discount: false,
        image: {
            src: './assets/images/greenfield_black.jpg',
        },
        brand: 'Greenfield',
        type: 'чай',
        box: 'листовой',
        color: 'черный',
        country: 'Индонезия',
        price: 11,
        date: 2021,
    },
    {
        id: 21,
        discount_value: 50,
        discount: false,
        image: {
            src: './assets/images/greenfield_white.jpg',
        },
        brand: 'Greenfield',
        type: 'чай',
        box: 'листовой',
        color: 'белый',
        country: 'Индонезия',
        price: 10,
        date: 2022,
    },
    {
        id: 22,
        discount_value: 50,
        discount: false,
        image: {
            src: './assets/images/greenfield_red.jpg',
        },
        brand: 'Greenfield',
        type: 'чай',
        box: 'листовой',
        color: 'красный',
        country: 'Англия',
        price: 10,
        date: 2018,
    },
];
